// Clé API Google Books (gratuite). Sans clé, Google partage un quota journalier
// entre tous les sites et refuse souvent de répondre. Voir le README pour la créer.
const GOOGLE_API_KEY = "AIzaSyCrrm7C1Pwzo6FpWHagdjTs7yU-Jh5R_Qs";

// Avis des lecteurs partagés (Cloud Firestore). Laisser vide pour enregistrer
// les avis uniquement dans le navigateur de chaque visiteur. Voir le README.
const FIREBASE_PROJECT_ID = "test-biblio-998a1";
// Clé du projet Firebase ; si vide, GOOGLE_API_KEY est utilisée.
const FIREBASE_API_KEY = "AIzaSyB7UPMwlJ28K2h4DTyBKJhm0gsBwTgqOuM";

// Données statiques : genres, auteurs mis en avant et librairies en ligne.

// Genres regroupés par famille. Chaque genre indique la requête à utiliser
// pour chaque source de données :
//  - google      : valeur passée à "subject:" dans l'API Google Books
//  - openlibrary : valeur passée au paramètre "subject" d'Open Library
const GENRE_GROUPS = [
  { name: "Littérature", genres: [
    { id: "romans", name: "Romans", icon: "📖", google: "fiction", openlibrary: "fiction" },
    { id: "litterature-francaise", name: "Littérature française", icon: "🇫🇷", google: "literary", openlibrary: "french literature" },
    { id: "classiques", name: "Classiques", icon: "🏛️", google: "classics", openlibrary: "classic literature" },
    { id: "policier", name: "Policier", icon: "🔍", google: "detective", openlibrary: "detective and mystery stories" },
    { id: "thriller", name: "Thriller & Suspense", icon: "🔪", google: "thrillers", openlibrary: "thrillers" },
    { id: "roman-historique", name: "Roman historique", icon: "⚔️", google: "historical fiction", openlibrary: "historical fiction" },
    { id: "romance", name: "Romance", icon: "💕", google: "romance", openlibrary: "romance" },
    { id: "nouvelles", name: "Nouvelles", icon: "✒️", google: "short stories", openlibrary: "short stories" },
    { id: "poesie", name: "Poésie", icon: "🪶", google: "poetry", openlibrary: "poetry" },
    { id: "theatre", name: "Théâtre", icon: "🎭", google: "drama", openlibrary: "drama" },
    { id: "humour", name: "Humour", icon: "😂", google: "humor", openlibrary: "humor" },
    { id: "aventure", name: "Aventure", icon: "🧭", google: "action & adventure", openlibrary: "adventure stories" },
    { id: "temoignages", name: "Témoignages & récits de vie", icon: "🗣️", google: "personal memoirs", openlibrary: "autobiography" },
    { id: "true-crime", name: "True crime", icon: "🕵️", google: "true crime", openlibrary: "true crime" },
  ] },
  { name: "Imaginaire", genres: [
    { id: "science-fiction", name: "Science-fiction", icon: "🚀", google: "science fiction", openlibrary: "science fiction" },
    { id: "fantasy", name: "Fantasy", icon: "🐉", google: "fantasy", openlibrary: "fantasy" },
    { id: "horreur", name: "Horreur", icon: "👻", google: "horror", openlibrary: "horror" },
    { id: "fantastique", name: "Fantastique & Paranormal", icon: "🔮", google: "paranormal", openlibrary: "paranormal fiction" },
    { id: "dystopie", name: "Dystopie", icon: "🏚️", google: "dystopian", openlibrary: "dystopias" },
    { id: "romantasy", name: "Romantasy", icon: "🗡️", google: "fantasy romance", openlibrary: "fantasy romance" },
    { id: "uchronie", name: "Uchronie", icon: "⏳", google: "alternative history", openlibrary: "alternative histories (fiction)" },
    { id: "steampunk", name: "Steampunk", icon: "⚙️", google: "steampunk", openlibrary: "steampunk" },
    { id: "post-apo", name: "Post-apocalyptique", icon: "☢️", google: "post-apocalyptic", openlibrary: "post-apocalyptic fiction" },
  ] },
  { name: "Mangas & BD", genres: [
    { id: "manga", name: "Mangas", icon: "🎌", google: "manga", openlibrary: "manga" },
    { id: "shonen", name: "Shōnen", icon: "🔥", google: "shonen", openlibrary: "shonen" },
    { id: "shojo", name: "Shōjo", icon: "🌸", google: "shojo", openlibrary: "shojo" },
    { id: "seinen", name: "Seinen", icon: "🗡️", google: "seinen", openlibrary: "seinen" },
    { id: "light-novel", name: "Light novels", icon: "📘", google: "light novels", openlibrary: "light novels" },
    { id: "bd", name: "Bandes dessinées", icon: "💬", google: "comics", openlibrary: "comic books, strips" },
    { id: "comics", name: "Comics & super-héros", icon: "🦸", google: "superheroes", openlibrary: "superheroes" },
    { id: "roman-graphique", name: "Romans graphiques", icon: "🖋️", google: "graphic novels", openlibrary: "graphic novels" },
    { id: "manhwa", name: "Manhwa & webtoons", icon: "🇰🇷", google: "manhwa", openlibrary: "manhwa" },
  ] },
  { name: "Jeunesse", genres: [
    { id: "albums", name: "Albums (0-6 ans)", icon: "🧸", google: "picture books", openlibrary: "picture books" },
    { id: "jeunesse", name: "Romans jeunesse", icon: "🎈", google: "juvenile fiction", openlibrary: "juvenile fiction" },
    { id: "young-adult", name: "Young Adult", icon: "🎒", google: "young adult fiction", openlibrary: "young adult fiction" },
    { id: "contes", name: "Contes & légendes", icon: "🏰", google: "fairy tales", openlibrary: "fairy tales" },
    { id: "documentaires-jeunesse", name: "Documentaires jeunesse", icon: "🔭", google: "juvenile nonfiction", openlibrary: "juvenile literature" },
  ] },
  { name: "Savoirs & essais", genres: [
    { id: "histoire", name: "Histoire", icon: "📜", google: "history", openlibrary: "history" },
    { id: "biographies", name: "Biographies", icon: "👤", google: "biography", openlibrary: "biography" },
    { id: "philosophie", name: "Philosophie", icon: "🤔", google: "philosophy", openlibrary: "philosophy" },
    { id: "sciences", name: "Sciences", icon: "🔬", google: "science", openlibrary: "science" },
    { id: "psychologie", name: "Psychologie", icon: "🧠", google: "psychology", openlibrary: "psychology" },
    { id: "politique", name: "Politique", icon: "🏛", google: "political science", openlibrary: "political science" },
    { id: "societe", name: "Société & sociologie", icon: "👥", google: "social science", openlibrary: "sociology" },
    { id: "economie", name: "Économie & business", icon: "💼", google: "business", openlibrary: "business" },
    { id: "droit", name: "Droit", icon: "⚖️", google: "law", openlibrary: "law" },
    { id: "religion", name: "Religion & spiritualité", icon: "🕊️", google: "religion", openlibrary: "religion" },
    { id: "art", name: "Art & photographie", icon: "🎨", google: "art", openlibrary: "art" },
    { id: "musique", name: "Musique", icon: "🎵", google: "music", openlibrary: "music" },
    { id: "cinema", name: "Cinéma", icon: "🎬", google: "performing arts", openlibrary: "motion pictures" },
    { id: "nature", name: "Nature & environnement", icon: "🌿", google: "nature", openlibrary: "nature" },
    { id: "informatique", name: "Informatique", icon: "💻", google: "computers", openlibrary: "computers" },
    { id: "langues", name: "Langues", icon: "🗣️", google: "foreign language study", openlibrary: "language and languages" },
    { id: "education", name: "Éducation", icon: "🎓", google: "education", openlibrary: "education" },
    { id: "mythologie", name: "Mythologie", icon: "🏺", google: "mythology", openlibrary: "mythology" },
    { id: "astronomie", name: "Astronomie & espace", icon: "🔭", google: "astronomy", openlibrary: "astronomy" },
    { id: "ecologie", name: "Écologie & climat", icon: "🌍", google: "environmental", openlibrary: "environmental protection" },
    { id: "guerre", name: "Histoire militaire", icon: "🎖️", google: "military history", openlibrary: "military history" },
  ] },
  { name: "Vie pratique", genres: [
    { id: "cuisine", name: "Cuisine", icon: "🍳", google: "cooking", openlibrary: "cooking" },
    { id: "dev-perso", name: "Développement personnel", icon: "🌱", google: "self-help", openlibrary: "self-help" },
    { id: "sante", name: "Santé & bien-être", icon: "🩺", google: "health", openlibrary: "health" },
    { id: "sport", name: "Sport", icon: "⚽", google: "sports", openlibrary: "sports" },
    { id: "voyage", name: "Voyage", icon: "✈️", google: "travel", openlibrary: "travel" },
    { id: "jardinage", name: "Jardinage", icon: "🌻", google: "gardening", openlibrary: "gardening" },
    { id: "maison", name: "Maison & bricolage", icon: "🔨", google: "house & home", openlibrary: "do-it-yourself" },
    { id: "famille", name: "Famille & parentalité", icon: "👪", google: "family & relationships", openlibrary: "parenting" },
    { id: "animaux", name: "Animaux", icon: "🐾", google: "pets", openlibrary: "pets" },
    { id: "loisirs", name: "Loisirs créatifs", icon: "🧶", google: "crafts & hobbies", openlibrary: "handicraft" },
    { id: "jeux", name: "Jeux & énigmes", icon: "🧩", google: "games", openlibrary: "games" },
    { id: "mode-beaute", name: "Mode & beauté", icon: "💄", google: "beauty", openlibrary: "beauty, personal" },
  ] },
];

const GENRES = GENRE_GROUPS.flatMap(group => group.genres.map(g => ({ ...g, group: group.name })));

// Genres affichés sur la page d'accueil.
const HOME_GENRES = ["romans", "policier", "thriller", "science-fiction", "fantasy", "manga", "shonen", "bd", "jeunesse", "young-adult", "romance", "histoire"];

// Auteurs mis en avant, par catégorie (toute autre recherche par auteur reste possible).
const FEATURED_AUTHORS = [
  { name: "Victor Hugo", tag: "Classiques" },
  { name: "Albert Camus", tag: "Classiques" },
  { name: "Émile Zola", tag: "Classiques" },
  { name: "Alexandre Dumas", tag: "Classiques" },
  { name: "Gustave Flaubert", tag: "Classiques" },
  { name: "Honoré de Balzac", tag: "Classiques" },
  { name: "Guy de Maupassant", tag: "Classiques" },
  { name: "Stendhal", tag: "Classiques" },
  { name: "Marcel Proust", tag: "Classiques" },
  { name: "Molière", tag: "Classiques" },
  { name: "Jean de La Fontaine", tag: "Classiques" },
  { name: "Charles Baudelaire", tag: "Classiques" },
  { name: "Arthur Rimbaud", tag: "Classiques" },
  { name: "Voltaire", tag: "Classiques" },
  { name: "Simone de Beauvoir", tag: "Classiques" },
  { name: "Jean-Paul Sartre", tag: "Classiques" },
  { name: "Marguerite Duras", tag: "Classiques" },
  { name: "Antoine de Saint-Exupéry", tag: "Classiques" },
  { name: "Albert Cohen", tag: "Classiques" },
  { name: "George Orwell", tag: "Classiques" },
  { name: "Jane Austen", tag: "Classiques" },
  { name: "Fiodor Dostoïevski", tag: "Classiques" },
  { name: "Léon Tolstoï", tag: "Classiques" },
  { name: "Annie Ernaux", tag: "Littérature" },
  { name: "Michel Houellebecq", tag: "Littérature" },
  { name: "Patrick Modiano", tag: "Littérature" },
  { name: "J.M.G. Le Clézio", tag: "Littérature" },
  { name: "Leïla Slimani", tag: "Littérature" },
  { name: "Amélie Nothomb", tag: "Littérature" },
  { name: "Pierre Lemaitre", tag: "Littérature" },
  { name: "Éric-Emmanuel Schmitt", tag: "Littérature" },
  { name: "Delphine de Vigan", tag: "Littérature" },
  { name: "Virginie Despentes", tag: "Littérature" },
  { name: "Daniel Pennac", tag: "Littérature" },
  { name: "Romain Gary", tag: "Littérature" },
  { name: "Haruki Murakami", tag: "Littérature" },
  { name: "Gabriel García Márquez", tag: "Littérature" },
  { name: "Toni Morrison", tag: "Littérature" },
  { name: "Paulo Coelho", tag: "Littérature" },
  { name: "Kamel Daoud", tag: "Littérature" },
  { name: "Mohamed Mbougar Sarr", tag: "Littérature" },
  { name: "Guillaume Musso", tag: "Roman" },
  { name: "Marc Levy", tag: "Roman" },
  { name: "Virginie Grimaldi", tag: "Roman" },
  { name: "Mélissa Da Costa", tag: "Roman" },
  { name: "Valérie Perrin", tag: "Roman" },
  { name: "Aurélie Valognes", tag: "Roman" },
  { name: "Agnès Martin-Lugand", tag: "Roman" },
  { name: "Katherine Pancol", tag: "Roman" },
  { name: "Anna Gavalda", tag: "Roman" },
  { name: "Joël Dicker", tag: "Policier & thriller" },
  { name: "Fred Vargas", tag: "Policier & thriller" },
  { name: "Franck Thilliez", tag: "Policier & thriller" },
  { name: "Michel Bussi", tag: "Policier & thriller" },
  { name: "Bernard Minier", tag: "Policier & thriller" },
  { name: "Jean-Christophe Grangé", tag: "Policier & thriller" },
  { name: "Maxime Chattam", tag: "Policier & thriller" },
  { name: "Olivier Norek", tag: "Policier & thriller" },
  { name: "Georges Simenon", tag: "Policier & thriller" },
  { name: "Agatha Christie", tag: "Policier & thriller" },
  { name: "Harlan Coben", tag: "Policier & thriller" },
  { name: "Dan Brown", tag: "Policier & thriller" },
  { name: "Camilla Läckberg", tag: "Policier & thriller" },
  { name: "Stieg Larsson", tag: "Policier & thriller" },
  { name: "Arthur Conan Doyle", tag: "Policier & thriller" },
  { name: "Maurice Leblanc", tag: "Policier & thriller" },
  { name: "Jules Verne", tag: "Imaginaire" },
  { name: "Bernard Werber", tag: "Imaginaire" },
  { name: "Pierre Bordage", tag: "Imaginaire" },
  { name: "Alain Damasio", tag: "Imaginaire" },
  { name: "J.R.R. Tolkien", tag: "Imaginaire" },
  { name: "J.K. Rowling", tag: "Imaginaire" },
  { name: "George R.R. Martin", tag: "Imaginaire" },
  { name: "Stephen King", tag: "Imaginaire" },
  { name: "Isaac Asimov", tag: "Imaginaire" },
  { name: "Frank Herbert", tag: "Imaginaire" },
  { name: "Philip K. Dick", tag: "Imaginaire" },
  { name: "Terry Pratchett", tag: "Imaginaire" },
  { name: "Brandon Sanderson", tag: "Imaginaire" },
  { name: "Christelle Dabos", tag: "Imaginaire" },
  { name: "Pierre Bottero", tag: "Imaginaire" },
  { name: "H.P. Lovecraft", tag: "Imaginaire" },
  { name: "Eiichiro Oda", tag: "Manga" },
  { name: "Masashi Kishimoto", tag: "Manga" },
  { name: "Akira Toriyama", tag: "Manga" },
  { name: "Hajime Isayama", tag: "Manga" },
  { name: "Naoki Urasawa", tag: "Manga" },
  { name: "Tite Kubo", tag: "Manga" },
  { name: "Kohei Horikoshi", tag: "Manga" },
  { name: "Gege Akutami", tag: "Manga" },
  { name: "Koyoharu Gotouge", tag: "Manga" },
  { name: "Tatsuki Fujimoto", tag: "Manga" },
  { name: "Hiromu Arakawa", tag: "Manga" },
  { name: "Takehiko Inoue", tag: "Manga" },
  { name: "Kentaro Miura", tag: "Manga" },
  { name: "Yoshihiro Togashi", tag: "Manga" },
  { name: "Rumiko Takahashi", tag: "Manga" },
  { name: "Naoko Takeuchi", tag: "Manga" },
  { name: "CLAMP", tag: "Manga" },
  { name: "Osamu Tezuka", tag: "Manga" },
  { name: "Jirō Taniguchi", tag: "Manga" },
  { name: "Junji Ito", tag: "Manga" },
  { name: "Tsugumi Ohba", tag: "Manga" },
  { name: "Yusei Matsui", tag: "Manga" },
  { name: "ONE", tag: "Manga" },
  { name: "René Goscinny", tag: "BD" },
  { name: "Hergé", tag: "BD" },
  { name: "Albert Uderzo", tag: "BD" },
  { name: "Morris", tag: "BD" },
  { name: "Franquin", tag: "BD" },
  { name: "Peyo", tag: "BD" },
  { name: "Jean Van Hamme", tag: "BD" },
  { name: "Riad Sattouf", tag: "BD" },
  { name: "Joann Sfar", tag: "BD" },
  { name: "Marjane Satrapi", tag: "BD" },
  { name: "Enki Bilal", tag: "BD" },
  { name: "Moebius", tag: "BD" },
  { name: "Zep", tag: "BD" },
  { name: "Bastien Vivès", tag: "BD" },
  { name: "Emmanuel Lepage", tag: "BD" },
  { name: "Christophe Arleston", tag: "BD" },
  { name: "Tony Valente", tag: "BD" },
  { name: "Roald Dahl", tag: "Jeunesse" },
  { name: "Claude Ponti", tag: "Jeunesse" },
  { name: "Tomi Ungerer", tag: "Jeunesse" },
  { name: "Rick Riordan", tag: "Jeunesse" },
  { name: "Suzanne Collins", tag: "Jeunesse" },
  { name: "Christopher Paolini", tag: "Jeunesse" },
  { name: "Philip Pullman", tag: "Jeunesse" },
  { name: "Timothée de Fombelle", tag: "Jeunesse" },
  { name: "Jeff Kinney", tag: "Jeunesse" },
  { name: "Yuval Noah Harari", tag: "Essais" },
  { name: "Boris Cyrulnik", tag: "Essais" },
  { name: "Edgar Morin", tag: "Essais" },
  { name: "Michel Onfray", tag: "Essais" },
  { name: "Frédéric Lenoir", tag: "Essais" },
  { name: "Christophe André", tag: "Essais" },
  { name: "Pierre Bourdieu", tag: "Essais" },
  { name: "Thomas Piketty", tag: "Essais" },
  { name: "Hubert Reeves", tag: "Essais" },
  { name: "Albert Jacquard", tag: "Essais" },
  { name: "Jean Racine", tag: "Classiques" },
  { name: "Pierre Corneille", tag: "Classiques" },
  { name: "Montesquieu", tag: "Classiques" },
  { name: "Jean-Jacques Rousseau", tag: "Classiques" },
  { name: "Denis Diderot", tag: "Classiques" },
  { name: "Choderlos de Laclos", tag: "Classiques" },
  { name: "Madame de La Fayette", tag: "Classiques" },
  { name: "Alfred de Musset", tag: "Classiques" },
  { name: "Paul Verlaine", tag: "Classiques" },
  { name: "Guillaume Apollinaire", tag: "Classiques" },
  { name: "Colette", tag: "Classiques" },
  { name: "Louis-Ferdinand Céline", tag: "Classiques" },
  { name: "André Gide", tag: "Classiques" },
  { name: "Marguerite Yourcenar", tag: "Classiques" },
  { name: "Boris Vian", tag: "Classiques" },
  { name: "Raymond Queneau", tag: "Classiques" },
  { name: "Georges Perec", tag: "Classiques" },
  { name: "Jean Giono", tag: "Classiques" },
  { name: "Marcel Pagnol", tag: "Classiques" },
  { name: "Hervé Bazin", tag: "Classiques" },
  { name: "Franz Kafka", tag: "Classiques" },
  { name: "Charles Dickens", tag: "Classiques" },
  { name: "Ernest Hemingway", tag: "Classiques" },
  { name: "F. Scott Fitzgerald", tag: "Classiques" },
  { name: "John Steinbeck", tag: "Classiques" },
  { name: "Oscar Wilde", tag: "Classiques" },
  { name: "Mary Shelley", tag: "Classiques" },
  { name: "Bram Stoker", tag: "Classiques" },
  { name: "Herman Melville", tag: "Classiques" },
  { name: "Virginia Woolf", tag: "Classiques" },
  { name: "Stefan Zweig", tag: "Classiques" },
  { name: "Umberto Eco", tag: "Classiques" },
  { name: "Mathias Énard", tag: "Littérature" },
  { name: "Laurent Gaudé", tag: "Littérature" },
  { name: "Alice Zeniter", tag: "Littérature" },
  { name: "Maylis de Kerangal", tag: "Littérature" },
  { name: "Sylvain Tesson", tag: "Littérature" },
  { name: "Emmanuel Carrère", tag: "Littérature" },
  { name: "Jean d'Ormesson", tag: "Littérature" },
  { name: "Tahar Ben Jelloun", tag: "Littérature" },
  { name: "Yasmina Khadra", tag: "Littérature" },
  { name: "Gaël Faye", tag: "Littérature" },
  { name: "Hervé Le Tellier", tag: "Littérature" },
  { name: "Muriel Barbery", tag: "Littérature" },
  { name: "Jonathan Littell", tag: "Littérature" },
  { name: "Kazuo Ishiguro", tag: "Littérature" },
  { name: "Margaret Atwood", tag: "Littérature" },
  { name: "Chimamanda Ngozi Adichie", tag: "Littérature" },
  { name: "Elena Ferrante", tag: "Littérature" },
  { name: "Khaled Hosseini", tag: "Littérature" },
  { name: "Carlos Ruiz Zafón", tag: "Littérature" },
  { name: "Sally Rooney", tag: "Littérature" },
  { name: "Françoise Bourdin", tag: "Roman" },
  { name: "Gilles Legardinier", tag: "Roman" },
  { name: "Raphaëlle Giordano", tag: "Roman" },
  { name: "Laurent Gounelle", tag: "Roman" },
  { name: "Tatiana de Rosnay", tag: "Roman" },
  { name: "Grégoire Delacourt", tag: "Roman" },
  { name: "Colleen Hoover", tag: "Romance & feel-good" },
  { name: "Morgane Moncomble", tag: "Romance & feel-good" },
  { name: "Anna Todd", tag: "Romance & feel-good" },
  { name: "Jojo Moyes", tag: "Romance & feel-good" },
  { name: "Nicholas Sparks", tag: "Romance & feel-good" },
  { name: "Danielle Steel", tag: "Romance & feel-good" },
  { name: "Sophie Kinsella", tag: "Romance & feel-good" },
  { name: "Emily Henry", tag: "Romance & feel-good" },
  { name: "Ali Hazelwood", tag: "Romance & feel-good" },
  { name: "Rebecca Yarros", tag: "Romance & feel-good" },
  { name: "Sarah J. Maas", tag: "Romance & feel-good" },
  { name: "Karine Giebel", tag: "Policier & thriller" },
  { name: "Caryl Férey", tag: "Policier & thriller" },
  { name: "Ian Manook", tag: "Policier & thriller" },
  { name: "Sandrine Collette", tag: "Policier & thriller" },
  { name: "Nicolas Beuglet", tag: "Policier & thriller" },
  { name: "Gaston Leroux", tag: "Policier & thriller" },
  { name: "Didier Daeninckx", tag: "Policier & thriller" },
  { name: "Henning Mankell", tag: "Policier & thriller" },
  { name: "Jo Nesbø", tag: "Policier & thriller" },
  { name: "Michael Connelly", tag: "Policier & thriller" },
  { name: "Patricia Cornwell", tag: "Policier & thriller" },
  { name: "Ken Follett", tag: "Policier & thriller" },
  { name: "John Grisham", tag: "Policier & thriller" },
  { name: "Dennis Lehane", tag: "Policier & thriller" },
  { name: "Lee Child", tag: "Policier & thriller" },
  { name: "Ursula K. Le Guin", tag: "Imaginaire" },
  { name: "Robin Hobb", tag: "Imaginaire" },
  { name: "Neil Gaiman", tag: "Imaginaire" },
  { name: "Ray Bradbury", tag: "Imaginaire" },
  { name: "Aldous Huxley", tag: "Imaginaire" },
  { name: "Arthur C. Clarke", tag: "Imaginaire" },
  { name: "Dan Simmons", tag: "Imaginaire" },
  { name: "Liu Cixin", tag: "Imaginaire" },
  { name: "Andrzej Sapkowski", tag: "Imaginaire" },
  { name: "Patrick Rothfuss", tag: "Imaginaire" },
  { name: "Jean-Philippe Jaworski", tag: "Imaginaire" },
  { name: "Pierre Pevel", tag: "Imaginaire" },
  { name: "Lionel Davoust", tag: "Imaginaire" },
  { name: "Joe Abercrombie", tag: "Imaginaire" },
  { name: "Becky Chambers", tag: "Imaginaire" },
  { name: "Hirohiko Araki", tag: "Manga" },
  { name: "Makoto Yukimura", tag: "Manga" },
  { name: "Sui Ishida", tag: "Manga" },
  { name: "Riichiro Inagaki", tag: "Manga" },
  { name: "Ken Wakui", tag: "Manga" },
  { name: "Tatsuya Endo", tag: "Manga" },
  { name: "Hideaki Sorachi", tag: "Manga" },
  { name: "Kazue Kato", tag: "Manga" },
  { name: "Hiro Mashima", tag: "Manga" },
  { name: "Atsushi Ohkubo", tag: "Manga" },
  { name: "Yana Toboso", tag: "Manga" },
  { name: "Inio Asano", tag: "Manga" },
  { name: "Ai Yazawa", tag: "Manga" },
  { name: "Natsuki Takaya", tag: "Manga" },
  { name: "Mitsuru Adachi", tag: "Manga" },
  { name: "Katsuhiro Otomo", tag: "Manga" },
  { name: "Muneyuki Kaneshiro", tag: "Manga" },
  { name: "Yukinobu Tatsu", tag: "Manga" },
  { name: "Lewis Trondheim", tag: "BD" },
  { name: "Christophe Blain", tag: "BD" },
  { name: "Manu Larcenet", tag: "BD" },
  { name: "Fabcaro", tag: "BD" },
  { name: "Pénélope Bagieu", tag: "BD" },
  { name: "Catherine Meurisse", tag: "BD" },
  { name: "Mathieu Bablet", tag: "BD" },
  { name: "Philippe Geluck", tag: "BD" },
  { name: "Jean-Yves Ferri", tag: "BD" },
  { name: "Wilfrid Lupano", tag: "BD" },
  { name: "Guy Delisle", tag: "BD" },
  { name: "François Schuiten", tag: "BD" },
  { name: "Hermann", tag: "BD" },
  { name: "Juan Díaz Canales", tag: "BD" },
  { name: "Art Spiegelman", tag: "BD" },
  { name: "Alan Moore", tag: "BD" },
  { name: "Marie-Aude Murail", tag: "Jeunesse" },
  { name: "Susie Morgenstern", tag: "Jeunesse" },
  { name: "Jean-Jacques Sempé", tag: "Jeunesse" },
  { name: "Anthony Browne", tag: "Jeunesse" },
  { name: "Julia Donaldson", tag: "Jeunesse" },
  { name: "Geronimo Stilton", tag: "Jeunesse" },
  { name: "Enid Blyton", tag: "Jeunesse" },
  { name: "Lewis Carroll", tag: "Jeunesse" },
  { name: "C.S. Lewis", tag: "Jeunesse" },
  { name: "Cornelia Funke", tag: "Jeunesse" },
  { name: "Michael Morpurgo", tag: "Jeunesse" },
  { name: "John Green", tag: "Young Adult" },
  { name: "Veronica Roth", tag: "Young Adult" },
  { name: "Cassandra Clare", tag: "Young Adult" },
  { name: "Leigh Bardugo", tag: "Young Adult" },
  { name: "Stephenie Meyer", tag: "Young Adult" },
  { name: "Holly Black", tag: "Young Adult" },
  { name: "Victor Dixen", tag: "Young Adult" },
  { name: "Samantha Bailly", tag: "Young Adult" },
  { name: "Paul Éluard", tag: "Poésie & théâtre" },
  { name: "Louis Aragon", tag: "Poésie & théâtre" },
  { name: "Jacques Prévert", tag: "Poésie & théâtre" },
  { name: "Pablo Neruda", tag: "Poésie & théâtre" },
  { name: "Edmond Rostand", tag: "Poésie & théâtre" },
  { name: "Eugène Ionesco", tag: "Poésie & théâtre" },
  { name: "Samuel Beckett", tag: "Poésie & théâtre" },
  { name: "Jean Anouilh", tag: "Poésie & théâtre" },
  { name: "Yasmina Reza", tag: "Poésie & théâtre" },
  { name: "William Shakespeare", tag: "Poésie & théâtre" },
  { name: "Marivaux", tag: "Poésie & théâtre" },
  { name: "Alfred Jarry", tag: "Poésie & théâtre" },
  { name: "Simone Weil", tag: "Essais" },
  { name: "Hannah Arendt", tag: "Essais" },
  { name: "Michel Foucault", tag: "Essais" },
  { name: "Claude Lévi-Strauss", tag: "Essais" },
  { name: "Roland Barthes", tag: "Essais" },
  { name: "Stephen Hawking", tag: "Essais" },
  { name: "Carlo Rovelli", tag: "Essais" },
  { name: "Étienne Klein", tag: "Essais" },
  { name: "Jared Diamond", tag: "Essais" },
  { name: "Daniel Kahneman", tag: "Essais" },
  { name: "Rutger Bregman", tag: "Essais" },
  { name: "Jean-Marc Jancovici", tag: "Essais" },
  { name: "Cyril Dion", tag: "Essais" },
  { name: "Mona Chollet", tag: "Essais" },
  { name: "Max Gallo", tag: "Histoire" },
  { name: "Alain Decaux", tag: "Histoire" },
  { name: "Stéphane Bern", tag: "Histoire" },
  { name: "Jacques Le Goff", tag: "Histoire" },
  { name: "Fernand Braudel", tag: "Histoire" },
  { name: "Antony Beevor", tag: "Histoire" },
  { name: "Patrick Boucheron", tag: "Histoire" },
  { name: "Don Miguel Ruiz", tag: "Développement personnel" },
  { name: "Eckhart Tolle", tag: "Développement personnel" },
  { name: "Dale Carnegie", tag: "Développement personnel" },
  { name: "James Clear", tag: "Développement personnel" },
  { name: "Mark Manson", tag: "Développement personnel" },
  { name: "Isabelle Filliozat", tag: "Développement personnel" },
  { name: "Fabrice Midal", tag: "Développement personnel" },
];

// Livres incontournables par catégorie (page « Incontournables »).
const MUST_READS = [
  { name: "Classiques français", books: [
    ["Les Misérables", "Victor Hugo"],
    ["Notre-Dame de Paris", "Victor Hugo"],
    ["L'Étranger", "Albert Camus"],
    ["La Peste", "Albert Camus"],
    ["Madame Bovary", "Gustave Flaubert"],
    ["Germinal", "Émile Zola"],
    ["Le Comte de Monte-Cristo", "Alexandre Dumas"],
    ["Les Trois Mousquetaires", "Alexandre Dumas"],
    ["Le Rouge et le Noir", "Stendhal"],
    ["Le Père Goriot", "Honoré de Balzac"],
    ["Bel-Ami", "Guy de Maupassant"],
    ["Candide", "Voltaire"],
    ["Le Petit Prince", "Antoine de Saint-Exupéry"],
    ["Du côté de chez Swann", "Marcel Proust"],
    ["Les Fleurs du mal", "Charles Baudelaire"],
    ["Cyrano de Bergerac", "Edmond Rostand"],
    ["Vingt mille lieues sous les mers", "Jules Verne"],
    ["Le Tour du monde en quatre-vingts jours", "Jules Verne"],
    ["Les Liaisons dangereuses", "Choderlos de Laclos"],
    ["La Gloire de mon père", "Marcel Pagnol"],
  ] },
  { name: "Littérature contemporaine", books: [
    ["La Vérité sur l'affaire Harry Quebert", "Joël Dicker"],
    ["Au revoir là-haut", "Pierre Lemaitre"],
    ["Chanson douce", "Leïla Slimani"],
    ["Les Années", "Annie Ernaux"],
    ["La Carte et le Territoire", "Michel Houellebecq"],
    ["L'Élégance du hérisson", "Muriel Barbery"],
    ["Changer l'eau des fleurs", "Valérie Perrin"],
    ["Petit Pays", "Gaël Faye"],
    ["L'Anomalie", "Hervé Le Tellier"],
    ["Réparer les vivants", "Maylis de Kerangal"],
    ["Stupeur et tremblements", "Amélie Nothomb"],
    ["Rien ne s'oppose à la nuit", "Delphine de Vigan"],
    ["Ensemble, c'est tout", "Anna Gavalda"],
    ["La Panthère des neiges", "Sylvain Tesson"],
    ["Les Bienveillantes", "Jonathan Littell"],
  ] },
  { name: "Littérature étrangère", books: [
    ["1984", "George Orwell"],
    ["Cent ans de solitude", "Gabriel García Márquez"],
    ["L'Ombre du vent", "Carlos Ruiz Zafón"],
    ["Les Cerfs-volants de Kaboul", "Khaled Hosseini"],
    ["La Servante écarlate", "Margaret Atwood"],
    ["Orgueil et Préjugés", "Jane Austen"],
    ["Crime et Châtiment", "Fiodor Dostoïevski"],
    ["Le Vieil Homme et la Mer", "Ernest Hemingway"],
    ["Des souris et des hommes", "John Steinbeck"],
    ["Kafka sur le rivage", "Haruki Murakami"],
    ["L'Amie prodigieuse", "Elena Ferrante"],
    ["Le Nom de la rose", "Umberto Eco"],
  ] },
  { name: "Policier & thriller", books: [
    ["Ils étaient dix", "Agatha Christie"],
    ["Le Chien des Baskerville", "Arthur Conan Doyle"],
    ["Arsène Lupin, gentleman cambrioleur", "Maurice Leblanc"],
    ["Le Mystère de la chambre jaune", "Gaston Leroux"],
    ["Les Hommes qui n'aimaient pas les femmes", "Stieg Larsson"],
    ["Pars vite et reviens tard", "Fred Vargas"],
    ["Nymphéas noirs", "Michel Bussi"],
    ["Le Syndrome E", "Franck Thilliez"],
    ["Glacé", "Bernard Minier"],
    ["Les Rivières pourpres", "Jean-Christophe Grangé"],
    ["Da Vinci Code", "Dan Brown"],
    ["Shutter Island", "Dennis Lehane"],
  ] },
  { name: "Imaginaire", books: [
    ["Le Seigneur des anneaux", "J.R.R. Tolkien"],
    ["Harry Potter à l'école des sorciers", "J.K. Rowling"],
    ["Dune", "Frank Herbert"],
    ["Fondation", "Isaac Asimov"],
    ["Le Trône de fer", "George R.R. Martin"],
    ["Les Fourmis", "Bernard Werber"],
    ["La Horde du Contrevent", "Alain Damasio"],
    ["Fahrenheit 451", "Ray Bradbury"],
    ["Le Meilleur des mondes", "Aldous Huxley"],
    ["La Passe-miroir", "Christelle Dabos"],
    ["Ça", "Stephen King"],
    ["Le Problème à trois corps", "Liu Cixin"],
    ["L'Assassin royal", "Robin Hobb"],
    ["Le Sorceleur", "Andrzej Sapkowski"],
  ] },
  { name: "Mangas", books: [
    ["One Piece", "Eiichiro Oda"],
    ["Naruto", "Masashi Kishimoto"],
    ["Dragon Ball", "Akira Toriyama"],
    ["L'Attaque des Titans", "Hajime Isayama"],
    ["Death Note", "Tsugumi Ohba"],
    ["Fullmetal Alchemist", "Hiromu Arakawa"],
    ["Demon Slayer", "Koyoharu Gotouge"],
    ["Jujutsu Kaisen", "Gege Akutami"],
    ["My Hero Academia", "Kohei Horikoshi"],
    ["Monster", "Naoki Urasawa"],
    ["Berserk", "Kentaro Miura"],
    ["Vagabond", "Takehiko Inoue"],
    ["Chainsaw Man", "Tatsuki Fujimoto"],
    ["Spy x Family", "Tatsuya Endo"],
    ["Fruits Basket", "Natsuki Takaya"],
    ["Nana", "Ai Yazawa"],
    ["Akira", "Katsuhiro Otomo"],
    ["Blue Lock", "Muneyuki Kaneshiro"],
  ] },
  { name: "Bandes dessinées", books: [
    ["Astérix le Gaulois", "René Goscinny"],
    ["Tintin au Tibet", "Hergé"],
    ["Lucky Luke", "Morris"],
    ["Gaston Lagaffe", "Franquin"],
    ["Les Schtroumpfs", "Peyo"],
    ["L'Arabe du futur", "Riad Sattouf"],
    ["Persepolis", "Marjane Satrapi"],
    ["Blacksad", "Juan Díaz Canales"],
    ["XIII", "Jean Van Hamme"],
    ["Largo Winch", "Jean Van Hamme"],
    ["Maus", "Art Spiegelman"],
    ["Le Chat du rabbin", "Joann Sfar"],
    ["Titeuf", "Zep"],
    ["Les Vieux Fourneaux", "Wilfrid Lupano"],
    ["Watchmen", "Alan Moore"],
  ] },
  { name: "Jeunesse & Young Adult", books: [
    ["Le Petit Nicolas", "René Goscinny"],
    ["Charlie et la chocolaterie", "Roald Dahl"],
    ["Matilda", "Roald Dahl"],
    ["Le Monde de Narnia", "C.S. Lewis"],
    ["Alice au pays des merveilles", "Lewis Carroll"],
    ["Hunger Games", "Suzanne Collins"],
    ["Percy Jackson", "Rick Riordan"],
    ["Nos étoiles contraires", "John Green"],
    ["Twilight", "Stephenie Meyer"],
    ["Divergente", "Veronica Roth"],
    ["Ewilan", "Pierre Bottero"],
    ["Journal d'un dégonflé", "Jeff Kinney"],
    ["Oh, boy !", "Marie-Aude Murail"],
    ["Tobie Lolness", "Timothée de Fombelle"],
  ] },
  { name: "Essais & vie pratique", books: [
    ["Sapiens", "Yuval Noah Harari"],
    ["Le Deuxième Sexe", "Simone de Beauvoir"],
    ["Une brève histoire du temps", "Stephen Hawking"],
    ["Les Quatre Accords toltèques", "Don Miguel Ruiz"],
    ["Système 1 / Système 2", "Daniel Kahneman"],
    ["Le Capital au XXIe siècle", "Thomas Piketty"],
    ["Journal d'Anne Frank", "Anne Frank"],
    ["L'Alchimiste", "Paulo Coelho"],
    ["Ta deuxième vie commence quand tu comprends que tu n'en as qu'une", "Raphaëlle Giordano"],
    ["Le Monde sans fin", "Christophe Blain"],
    ["Un rien peut tout changer", "James Clear"],
    ["Sorcières", "Mona Chollet"],
    ["Humanité", "Rutger Bregman"],
  ] },
];

// Librairies en ligne. "url" reçoit la requête (ISBN si disponible, sinon titre + auteur).
const STORES = [
  { id: "leslibraires", name: "Leslibraires.fr",     url: q => `https://www.leslibraires.fr/recherche/?q=${q}` },
  { id: "fnac",         name: "Fnac",                url: q => `https://www.fnac.com/SearchResult/ResultList.aspx?Search=${q}&sft=1&sa=0` },
  { id: "amazon",       name: "Amazon.fr",           url: q => `https://www.amazon.fr/s?k=${q}&i=stripbooks` },
  { id: "decitre",      name: "Decitre",             url: q => `https://www.decitre.fr/rechercher/result?q=${q}` },
  { id: "cultura",      name: "Cultura",             url: q => `https://www.cultura.com/search/results?search_query=${q}` },
  { id: "placedeslib",  name: "Place des Libraires", url: q => `https://www.placedeslibraires.fr/listeliv.php?base=allbooks&mots_recherche=${q}` },
  { id: "rakuten",      name: "Rakuten",             url: q => `https://fr.shopping.rakuten.com/search/${q}` },
];
