// Clé API Google Books (gratuite). Sans clé, Google partage un quota journalier
// entre tous les sites et refuse souvent de répondre. Voir le README pour la créer.
const GOOGLE_API_KEY = "AIzaSyCrrm7C1Pwzo6FpWHagdjTs7yU-Jh5R_Qs";

// Avis des lecteurs partagés (Cloud Firestore). Laisser vide pour enregistrer
// les avis uniquement dans le navigateur de chaque visiteur. Voir le README.
const FIREBASE_PROJECT_ID = "";
// Clé du projet Firebase ; si vide, GOOGLE_API_KEY est utilisée.
const FIREBASE_API_KEY = "";

// Données statiques : genres, auteurs mis en avant et librairies en ligne.

// Genres regroupés par famille. Chaque genre indique la requête à utiliser
// pour chaque source de données :
//  - google      : valeur passée à "subject:" dans l'API Google Books
//  - openlibrary : valeur passée au paramètre "subject" d'Open Library
const GENRE_GROUPS = [
  { name: "Littérature", genres: [
    { id: "romans", name: "Romans", icon: "📖", google: "fiction", openlibrary: "fiction" },
    { id: "litterature-francaise", name: "Littérature française", icon: "🇫🇷", google: "literary", openlibrary: "french literature" },
    { id: "classiques", name: "Classiques", icon: "🏛️", google: "classics", openlibrary: "classic literature" },
    { id: "policier", name: "Policier", icon: "🔍", google: "detective", openlibrary: "detective and mystery stories" },
    { id: "thriller", name: "Thriller & Suspense", icon: "🔪", google: "thrillers", openlibrary: "thrillers" },
    { id: "roman-historique", name: "Roman historique", icon: "⚔️", google: "historical fiction", openlibrary: "historical fiction" },
    { id: "romance", name: "Romance", icon: "💕", google: "romance", openlibrary: "romance" },
    { id: "nouvelles", name: "Nouvelles", icon: "✒️", google: "short stories", openlibrary: "short stories" },
    { id: "poesie", name: "Poésie", icon: "🪶", google: "poetry", openlibrary: "poetry" },
    { id: "theatre", name: "Théâtre", icon: "🎭", google: "drama", openlibrary: "drama" },
    { id: "humour", name: "Humour", icon: "😂", google: "humor", openlibrary: "humor" },
    { id: "aventure", name: "Aventure", icon: "🧭", google: "action & adventure", openlibrary: "adventure stories" },
  ] },
  { name: "Imaginaire", genres: [
    { id: "science-fiction", name: "Science-fiction", icon: "🚀", google: "science fiction", openlibrary: "science fiction" },
    { id: "fantasy", name: "Fantasy", icon: "🐉", google: "fantasy", openlibrary: "fantasy" },
    { id: "horreur", name: "Horreur", icon: "👻", google: "horror", openlibrary: "horror" },
    { id: "fantastique", name: "Fantastique & Paranormal", icon: "🔮", google: "paranormal", openlibrary: "paranormal fiction" },
    { id: "dystopie", name: "Dystopie", icon: "🏚️", google: "dystopian", openlibrary: "dystopias" },
  ] },
  { name: "Mangas & BD", genres: [
    { id: "manga", name: "Mangas", icon: "🎌", google: "manga", openlibrary: "manga" },
    { id: "shonen", name: "Shōnen", icon: "🔥", google: "shonen", openlibrary: "shonen" },
    { id: "shojo", name: "Shōjo", icon: "🌸", google: "shojo", openlibrary: "shojo" },
    { id: "seinen", name: "Seinen", icon: "🗡️", google: "seinen", openlibrary: "seinen" },
    { id: "light-novel", name: "Light novels", icon: "📘", google: "light novels", openlibrary: "light novels" },
    { id: "bd", name: "Bandes dessinées", icon: "💬", google: "comics", openlibrary: "comic books, strips" },
    { id: "comics", name: "Comics & super-héros", icon: "🦸", google: "superheroes", openlibrary: "superheroes" },
    { id: "roman-graphique", name: "Romans graphiques", icon: "🖋️", google: "graphic novels", openlibrary: "graphic novels" },
  ] },
  { name: "Jeunesse", genres: [
    { id: "albums", name: "Albums (0-6 ans)", icon: "🧸", google: "picture books", openlibrary: "picture books" },
    { id: "jeunesse", name: "Romans jeunesse", icon: "🎈", google: "juvenile fiction", openlibrary: "juvenile fiction" },
    { id: "young-adult", name: "Young Adult", icon: "🎒", google: "young adult fiction", openlibrary: "young adult fiction" },
    { id: "contes", name: "Contes & légendes", icon: "🏰", google: "fairy tales", openlibrary: "fairy tales" },
    { id: "documentaires-jeunesse", name: "Documentaires jeunesse", icon: "🔭", google: "juvenile nonfiction", openlibrary: "juvenile literature" },
  ] },
  { name: "Savoirs & essais", genres: [
    { id: "histoire", name: "Histoire", icon: "📜", google: "history", openlibrary: "history" },
    { id: "biographies", name: "Biographies", icon: "👤", google: "biography", openlibrary: "biography" },
    { id: "philosophie", name: "Philosophie", icon: "🤔", google: "philosophy", openlibrary: "philosophy" },
    { id: "sciences", name: "Sciences", icon: "🔬", google: "science", openlibrary: "science" },
    { id: "psychologie", name: "Psychologie", icon: "🧠", google: "psychology", openlibrary: "psychology" },
    { id: "politique", name: "Politique", icon: "🏛", google: "political science", openlibrary: "political science" },
    { id: "societe", name: "Société & sociologie", icon: "👥", google: "social science", openlibrary: "sociology" },
    { id: "economie", name: "Économie & business", icon: "💼", google: "business", openlibrary: "business" },
    { id: "droit", name: "Droit", icon: "⚖️", google: "law", openlibrary: "law" },
    { id: "religion", name: "Religion & spiritualité", icon: "🕊️", google: "religion", openlibrary: "religion" },
    { id: "art", name: "Art & photographie", icon: "🎨", google: "art", openlibrary: "art" },
    { id: "musique", name: "Musique", icon: "🎵", google: "music", openlibrary: "music" },
    { id: "cinema", name: "Cinéma", icon: "🎬", google: "performing arts", openlibrary: "motion pictures" },
    { id: "nature", name: "Nature & environnement", icon: "🌿", google: "nature", openlibrary: "nature" },
    { id: "informatique", name: "Informatique", icon: "💻", google: "computers", openlibrary: "computers" },
    { id: "langues", name: "Langues", icon: "🗣️", google: "foreign language study", openlibrary: "language and languages" },
    { id: "education", name: "Éducation", icon: "🎓", google: "education", openlibrary: "education" },
  ] },
  { name: "Vie pratique", genres: [
    { id: "cuisine", name: "Cuisine", icon: "🍳", google: "cooking", openlibrary: "cooking" },
    { id: "dev-perso", name: "Développement personnel", icon: "🌱", google: "self-help", openlibrary: "self-help" },
    { id: "sante", name: "Santé & bien-être", icon: "🩺", google: "health", openlibrary: "health" },
    { id: "sport", name: "Sport", icon: "⚽", google: "sports", openlibrary: "sports" },
    { id: "voyage", name: "Voyage", icon: "✈️", google: "travel", openlibrary: "travel" },
    { id: "jardinage", name: "Jardinage", icon: "🌻", google: "gardening", openlibrary: "gardening" },
    { id: "maison", name: "Maison & bricolage", icon: "🔨", google: "house & home", openlibrary: "do-it-yourself" },
    { id: "famille", name: "Famille & parentalité", icon: "👪", google: "family & relationships", openlibrary: "parenting" },
    { id: "animaux", name: "Animaux", icon: "🐾", google: "pets", openlibrary: "pets" },
    { id: "loisirs", name: "Loisirs créatifs", icon: "🧶", google: "crafts & hobbies", openlibrary: "handicraft" },
    { id: "jeux", name: "Jeux & énigmes", icon: "🧩", google: "games", openlibrary: "games" },
  ] },
];

const GENRES = GENRE_GROUPS.flatMap(group => group.genres.map(g => ({ ...g, group: group.name })));

// Genres affichés sur la page d'accueil.
const HOME_GENRES = ["romans", "policier", "thriller", "science-fiction", "fantasy", "manga", "shonen", "bd", "jeunesse", "young-adult", "romance", "histoire"];

// Auteurs mis en avant, par catégorie (toute autre recherche par auteur reste possible).
const FEATURED_AUTHORS = [
  { name: "Victor Hugo", tag: "Classiques" },
  { name: "Albert Camus", tag: "Classiques" },
  { name: "Émile Zola", tag: "Classiques" },
  { name: "Alexandre Dumas", tag: "Classiques" },
  { name: "Gustave Flaubert", tag: "Classiques" },
  { name: "Honoré de Balzac", tag: "Classiques" },
  { name: "Guy de Maupassant", tag: "Classiques" },
  { name: "Stendhal", tag: "Classiques" },
  { name: "Marcel Proust", tag: "Classiques" },
  { name: "Molière", tag: "Classiques" },
  { name: "Jean de La Fontaine", tag: "Classiques" },
  { name: "Charles Baudelaire", tag: "Classiques" },
  { name: "Arthur Rimbaud", tag: "Classiques" },
  { name: "Voltaire", tag: "Classiques" },
  { name: "Simone de Beauvoir", tag: "Classiques" },
  { name: "Jean-Paul Sartre", tag: "Classiques" },
  { name: "Marguerite Duras", tag: "Classiques" },
  { name: "Antoine de Saint-Exupéry", tag: "Classiques" },
  { name: "Albert Cohen", tag: "Classiques" },
  { name: "George Orwell", tag: "Classiques" },
  { name: "Jane Austen", tag: "Classiques" },
  { name: "Fiodor Dostoïevski", tag: "Classiques" },
  { name: "Léon Tolstoï", tag: "Classiques" },
  { name: "Annie Ernaux", tag: "Littérature" },
  { name: "Michel Houellebecq", tag: "Littérature" },
  { name: "Patrick Modiano", tag: "Littérature" },
  { name: "J.M.G. Le Clézio", tag: "Littérature" },
  { name: "Leïla Slimani", tag: "Littérature" },
  { name: "Amélie Nothomb", tag: "Littérature" },
  { name: "Pierre Lemaitre", tag: "Littérature" },
  { name: "Éric-Emmanuel Schmitt", tag: "Littérature" },
  { name: "Delphine de Vigan", tag: "Littérature" },
  { name: "Virginie Despentes", tag: "Littérature" },
  { name: "Daniel Pennac", tag: "Littérature" },
  { name: "Romain Gary", tag: "Littérature" },
  { name: "Haruki Murakami", tag: "Littérature" },
  { name: "Gabriel García Márquez", tag: "Littérature" },
  { name: "Toni Morrison", tag: "Littérature" },
  { name: "Paulo Coelho", tag: "Littérature" },
  { name: "Kamel Daoud", tag: "Littérature" },
  { name: "Mohamed Mbougar Sarr", tag: "Littérature" },
  { name: "Guillaume Musso", tag: "Roman" },
  { name: "Marc Levy", tag: "Roman" },
  { name: "Virginie Grimaldi", tag: "Roman" },
  { name: "Mélissa Da Costa", tag: "Roman" },
  { name: "Valérie Perrin", tag: "Roman" },
  { name: "Aurélie Valognes", tag: "Roman" },
  { name: "Agnès Martin-Lugand", tag: "Roman" },
  { name: "Katherine Pancol", tag: "Roman" },
  { name: "Anna Gavalda", tag: "Roman" },
  { name: "Joël Dicker", tag: "Policier & thriller" },
  { name: "Fred Vargas", tag: "Policier & thriller" },
  { name: "Franck Thilliez", tag: "Policier & thriller" },
  { name: "Michel Bussi", tag: "Policier & thriller" },
  { name: "Bernard Minier", tag: "Policier & thriller" },
  { name: "Jean-Christophe Grangé", tag: "Policier & thriller" },
  { name: "Maxime Chattam", tag: "Policier & thriller" },
  { name: "Olivier Norek", tag: "Policier & thriller" },
  { name: "Georges Simenon", tag: "Policier & thriller" },
  { name: "Agatha Christie", tag: "Policier & thriller" },
  { name: "Harlan Coben", tag: "Policier & thriller" },
  { name: "Dan Brown", tag: "Policier & thriller" },
  { name: "Camilla Läckberg", tag: "Policier & thriller" },
  { name: "Stieg Larsson", tag: "Policier & thriller" },
  { name: "Arthur Conan Doyle", tag: "Policier & thriller" },
  { name: "Maurice Leblanc", tag: "Policier & thriller" },
  { name: "Jules Verne", tag: "Imaginaire" },
  { name: "Bernard Werber", tag: "Imaginaire" },
  { name: "Pierre Bordage", tag: "Imaginaire" },
  { name: "Alain Damasio", tag: "Imaginaire" },
  { name: "J.R.R. Tolkien", tag: "Imaginaire" },
  { name: "J.K. Rowling", tag: "Imaginaire" },
  { name: "George R.R. Martin", tag: "Imaginaire" },
  { name: "Stephen King", tag: "Imaginaire" },
  { name: "Isaac Asimov", tag: "Imaginaire" },
  { name: "Frank Herbert", tag: "Imaginaire" },
  { name: "Philip K. Dick", tag: "Imaginaire" },
  { name: "Terry Pratchett", tag: "Imaginaire" },
  { name: "Brandon Sanderson", tag: "Imaginaire" },
  { name: "Christelle Dabos", tag: "Imaginaire" },
  { name: "Pierre Bottero", tag: "Imaginaire" },
  { name: "H.P. Lovecraft", tag: "Imaginaire" },
  { name: "Eiichiro Oda", tag: "Manga" },
  { name: "Masashi Kishimoto", tag: "Manga" },
  { name: "Akira Toriyama", tag: "Manga" },
  { name: "Hajime Isayama", tag: "Manga" },
  { name: "Naoki Urasawa", tag: "Manga" },
  { name: "Tite Kubo", tag: "Manga" },
  { name: "Kohei Horikoshi", tag: "Manga" },
  { name: "Gege Akutami", tag: "Manga" },
  { name: "Koyoharu Gotouge", tag: "Manga" },
  { name: "Tatsuki Fujimoto", tag: "Manga" },
  { name: "Hiromu Arakawa", tag: "Manga" },
  { name: "Takehiko Inoue", tag: "Manga" },
  { name: "Kentaro Miura", tag: "Manga" },
  { name: "Yoshihiro Togashi", tag: "Manga" },
  { name: "Rumiko Takahashi", tag: "Manga" },
  { name: "Naoko Takeuchi", tag: "Manga" },
  { name: "CLAMP", tag: "Manga" },
  { name: "Osamu Tezuka", tag: "Manga" },
  { name: "Jirō Taniguchi", tag: "Manga" },
  { name: "Junji Ito", tag: "Manga" },
  { name: "Tsugumi Ohba", tag: "Manga" },
  { name: "Yusei Matsui", tag: "Manga" },
  { name: "ONE", tag: "Manga" },
  { name: "René Goscinny", tag: "BD" },
  { name: "Hergé", tag: "BD" },
  { name: "Albert Uderzo", tag: "BD" },
  { name: "Morris", tag: "BD" },
  { name: "Franquin", tag: "BD" },
  { name: "Peyo", tag: "BD" },
  { name: "Jean Van Hamme", tag: "BD" },
  { name: "Riad Sattouf", tag: "BD" },
  { name: "Joann Sfar", tag: "BD" },
  { name: "Marjane Satrapi", tag: "BD" },
  { name: "Enki Bilal", tag: "BD" },
  { name: "Moebius", tag: "BD" },
  { name: "Zep", tag: "BD" },
  { name: "Bastien Vivès", tag: "BD" },
  { name: "Emmanuel Lepage", tag: "BD" },
  { name: "Christophe Arleston", tag: "BD" },
  { name: "Tony Valente", tag: "BD" },
  { name: "Roald Dahl", tag: "Jeunesse" },
  { name: "Claude Ponti", tag: "Jeunesse" },
  { name: "Tomi Ungerer", tag: "Jeunesse" },
  { name: "Rick Riordan", tag: "Jeunesse" },
  { name: "Suzanne Collins", tag: "Jeunesse" },
  { name: "Christopher Paolini", tag: "Jeunesse" },
  { name: "Philip Pullman", tag: "Jeunesse" },
  { name: "Timothée de Fombelle", tag: "Jeunesse" },
  { name: "Jeff Kinney", tag: "Jeunesse" },
  { name: "Yuval Noah Harari", tag: "Essais" },
  { name: "Boris Cyrulnik", tag: "Essais" },
  { name: "Edgar Morin", tag: "Essais" },
  { name: "Michel Onfray", tag: "Essais" },
  { name: "Frédéric Lenoir", tag: "Essais" },
  { name: "Christophe André", tag: "Essais" },
  { name: "Pierre Bourdieu", tag: "Essais" },
  { name: "Thomas Piketty", tag: "Essais" },
  { name: "Hubert Reeves", tag: "Essais" },
  { name: "Albert Jacquard", tag: "Essais" },
];

// Librairies en ligne. "url" reçoit la requête (ISBN si disponible, sinon titre + auteur).
const STORES = [
  { id: "leslibraires", name: "Leslibraires.fr",     url: q => `https://www.leslibraires.fr/recherche/?q=${q}` },
  { id: "fnac",         name: "Fnac",                url: q => `https://www.fnac.com/SearchResult/ResultList.aspx?Search=${q}&sft=1&sa=0` },
  { id: "amazon",       name: "Amazon.fr",           url: q => `https://www.amazon.fr/s?k=${q}&i=stripbooks` },
  { id: "decitre",      name: "Decitre",             url: q => `https://www.decitre.fr/rechercher/result?q=${q}` },
  { id: "cultura",      name: "Cultura",             url: q => `https://www.cultura.com/search/results?search_query=${q}` },
  { id: "placedeslib",  name: "Place des Libraires", url: q => `https://www.placedeslibraires.fr/listeliv.php?base=allbooks&mots_recherche=${q}` },
  { id: "rakuten",      name: "Rakuten",             url: q => `https://fr.shopping.rakuten.com/search/${q}` },
];
