const fs=require('fs'), vm=require('vm'); const R='/home/user/Site-test-A/';
const ctx={document:{getElementById:()=>({})},localStorage:{getItem:()=>null,setItem(){}},sessionStorage:{getItem:()=>null,setItem(){}},console,URLSearchParams};
vm.createContext(ctx);
for(const f of ['data.js','js/core/util.js','js/services/sources.js','js/services/quality.js']) vm.runInContext(fs.readFileSync(R+f,'utf8'),ctx,{filename:f});
const r=c=>vm.runInContext(c,ctx);
const B=(title,authors,extra={})=>({id:Math.random().toString(36),title,authors,year:'',publisher:'',pages:'',categories:[],description:'',isbn:'',covers:[],...extra});
ctx.B=B;
console.log('norm:', r(`norm("L'Étranger — Œuvre")`));
console.log('fuzzy "rowlng" vs rowling:', r(`tokenMatch("rowlng",["rowling"])`), '| "hugo" vs "hugues":', r(`tokenMatch("hugo",["hugues"])`));
const wk=r(`[workKey(B("Le Petit Prince",["Antoine de Saint-Exupéry"])), workKey(B("Le Petit Prince (Folio)",["Antoine de Saint-Exupéry"])), workKey(B("Le petit prince — Édition collector",["A. de Saint-Exupéry"])), workKey(B("One Piece - Tome 1",["Eiichiro Oda"])), workKey(B("One Piece",["Eiichiro Oda"],{})) , workKey(B("One Piece — Tome 2",["Eiichiro Oda"]))]`);
console.log('workKeys:', wk);
const d=r(`dedupeWorks([B("Le Petit Prince",["Antoine de Saint-Exupéry"]),B("Le Petit Prince (Folio)",["Antoine de Saint-Exupéry"],{isbn:"9782070612758",covers:["x"]}),B("One Piece - Tome 1",["Eiichiro Oda"]),B("One Piece - Tome 2",["Eiichiro Oda"])]).map(b=>b.title+" ["+(b.editions||1)+" éd., isbn "+b.isbn+"]")`);
console.log('dedupe:', d);
const g=r(`GENRES.find(x=>x.id==="policier")`); ctx.g=g;
console.log('faux positifs policier:', r(`[B("Le roman policier",["Y. Reuter"],{categories:["Literary Criticism"]}), B("Fiche de lecture : Les Rivières pourpres",["X"]), B("Nymphéas noirs",["Michel Bussi"],{categories:["Fiction / Mystery & Detective"]})].map(b=>b.title+" → "+(isGenreFalsePositive(b,g)?"EXCLU":"gardé"))`));
console.log('pertinence "harry potter ecole":', r(`rankByRelevance([B("Guide Harry Potter",["X"]),B("Harry Potter à l'école des sorciers",["J.K. Rowling"],{covers:["c"]}),B("Les sorciers de la mer",["Z"])],{type:"all",value:"harry potter ecole"}).map(b=>b.title)`));
console.log('auteur "rowlng":', r(`rankByRelevance([B("Livre A",["Autre Auteur"]),B("Harry Potter",["J.K. Rowling"])],{type:"author",value:"J.K. Rowlng"}).map(b=>b.title)`));
console.log('suggest "vict hu":', r(`suggest("vict hu").map(e=>e.type+":"+e.label)`));
console.log('suggest "one pie":', r(`suggest("one pie").map(e=>e.type+":"+e.label)`));
console.log('didYouMean "harri poter":', r(`didYouMean("harri poterr").map(e=>e.label)`));
console.log('didYouMean "camu":', r(`didYouMean("camu").map(e=>e.label)`));
console.log('didYouMean "dostoievsky":', r(`didYouMean("dostoievsky").map(e=>e.label)`));
console.log('authorVariant:', r(`[authorVariant("J.K. Rowling"),authorVariant("Antoine de Saint-Exupéry"),authorVariant("Hergé")]`));
